Repository Codify-Club-Berkeley/internal-management-system, pull requests merged in 2023-11, with the labels that each got.

#34 started working on meetings
  src/app/api/meeting/[id]/route.ts
  src/app/api/meeting/route.ts
  src/lib/validators.ts
  src/middleware.ts
Labels: backend

#35 Improved update profile
  package.json
  pnpm-lock.yaml
  src/app/profile/[slug]/ProfileDataTable.tsx
  src/app/profile/[slug]/page.tsx
  src/app/profile/[slug]/pageState.ts
  src/lib/validators.ts
Labels: frontend

#47 Dietary Restrictions Multi Select temporary fix
  src/app/profile/[slug]/ProfileDataTable.tsx
  src/app/roster/RosterTable.tsx
  src/lib/validators.ts
Labels: frontend, small size
